### ISSUE TITLE
"현지 신청이" 오타

### ISSUE THREAD

**Issue by lexifdev** [ahastudio/agilefest#1]
"현**지** 신청이 예상인원보다 초과되어 마감되었습니다" 라는 문구는
"현**재** 신청이 예상인원보다 초과되어 마감되었습니다" 라는 문구의 오타로 보입니다.

의도한 것이 아니라면 수정하는것이 좋겠습니다.

**Comment by lexifdev** [comment]
#2 풀 리퀘를 첨부합니다.

**Comment by ahastudio** [comment]
그러고 보니 “현지”란 표현이 의도처럼 보일 수도 있겠군요. 🤣
